---
title: "Output"
date: '`r paste("First created on April 01, 2023. Updated on", Sys.Date())`'
output:
  html_document: 
    df_print: kable
---

```{r, echo = FALSE}
knitr::opts_knit$set(root.dir = dirname(dirname(rstudioapi::getSourceEditorContext()$path)))
options(scipen=999)
```

As seen in [Quickstart](Quickstart.Rmd), `walkingcalculatr` generates a table of walk trips extracted from raw LBS data mapped to walkable areas within county census tracts.

### Extracted Walks and Mapped Walks Data Schema

The data schema from the walk table generated using `get_walks()` and `find_walkable()` is shown (see [Quickstart](Quickstart.Rmd)). For convenience, the function that calculates a given metric is outlined.

Metric	| Definition | Datatype | Example | Function Location |
--- | --- | --- | --- | --- |
userId | A unique identifier for a given LBS device. Each unique identifier has at least one location (via coordinates) over time.|`character`| 000-1111-aaaa-bbbb | ---|
time | A UNIX timestamp for a given **userId** position in time.|`numeric`|1655297278| --- |
lat | Latitude from set of coordinates in decimal degrees notation. | `numeric` | 40.42229 | --- |
lon | Longitude from set of coordinates in decimal degrees notation. | `numeric` | -79.78949 | --- |
accuracy | Horizontal accuracy of location in meters [m] | `numeric` | 4.5 | --- |
dist | For a given walk **userId and walkNum**, rolling distance [m] between two points over time | `numeric` | 3.4 | `get_walks()` |
vel	|	For a given walk **userId and walkNum**, rolling speed [m/s] between two points over time | `numeric` | 3.4 | `get_walks()` |
angle	| Angle between two points used to determine whether points are within walk. |`numeric`| 11.3| `get_walks()` |
walkNum	| A walk number for a given device **userId** | `numeric` | 2 | `get_walks()` |
total_walks_by_user	| The total number of walks for	a given a device **userId** | `numeric` | 13 | `get_walks()` |
numDaysActive	|	The total number of days given device has been active |`numeric` | 30 | `get_walks()` |
numPoints	| The total number of pings for	a given a walk | `numeric` | 32 | `get_walks()` |
walk_duration	|	Total cumulative duration [sec] for a given walk | `numeric` | 13.6 | `get_walks()`|
walk_distance	|	Total cumulative distance [m] for a given walk | `numeric` | 250.8 | `get_walks()`|
day_of_week	|	Category for day of week (weekday, weekend) | `character` | weekend | `get_walks()`|
walk_peak_cat	|	Category for walk peak hours (am_peak, pm_peak, off_peak). Defaults for each peak hours range are below, and can be set in get_walks() using a 24 hour format: AM peak start time is 6:00-10:00 M-F, PM peak default is 15:00-19:00 M-F. All other hours and days are off peak | `character` | off_peak | `get_walks()`|
IsUtilWalk | Categorical variable for whether a walk is utilitarian or recreational given a predetermined start-end buffer distance. Given a 100m buffer distance, if the first and last pings of a walk trip are within 100m of one another, then the walk trip is categorized as recreational. Otherwise, categorized as utilitarian. (default of 100m) |`character`| utilitarian | `get_walks()`|
buffer | Value [0, 1] designating whether ping is within a walkable area, with 1 indicating the LBS ping is in a walkable area and a 0 if not. |`numeric`|1| `find_walkable()` |
GEOID | U.S. Census unique identifier from the tigris package of the walkable area the ping is located in. If a ping is outside of walkable area, GEOID will be NA. If a ping is located in multiple walkable areas, then each `GEOID` of the intersected walkable areas will be returned and separated by a semicolon. |`character`| 06075010101 (single mapped area) __OR__ 06075010101;06075010555 (multiple mapped areas) | `find_walkable()` |
fraction | Proportion of pings within a given userId and walkNum walk trip that are within walkable areas. If the number of walk trip pings in walkable areas is > 0.75, the walk trip is considered to be in a walkable area.| `numeric` | 0.75 | `find_walkable()` |

### General and Census Tract Metric Summary Data Schema

Given a table of walk trips in walkable areas using `find_walkable()`, a summary table can be generated using either `metric_summary()` or `tract_metric_summary()`.

Metric	| Definition | Datatype | Example | Function Location |
--- | --- | --- | --- | --- |
GEOID | The 11-character unique identifier for each census tract from the U.S. Census | `character` | 06075010101 | `tract_metric_summary()` |
total_walks_in_walkable_areas | Total number of walks in walkable areas| `numeric`| 116,199 |`metric_summary()` & `tract_metric_summary()` |
total_distinct_users | Total number of distinct users (unique devices) |`numeric` | 19,213 | `metric_summary()` & `tract_metric_summary()` |
avg_dist_between_pings | Average distance [m] between pings within a given walk | `numeric`  | 543.07 | `metric_summary()` & `tract_metric_summary()` |
total_days_with_walks | Total number of days with walking trips in walkable areas | `numeric`  | 43 | `metric_summary()` & `tract_metric_summary()` |
recreational | Number of recreational walks  | `numeric` | 10 |`metric_summary()` & `tract_metric_summary()` |
utilitarian | Number of utilitarian walks | `numeric` | 20 |`metric_summary()` & `tract_metric_summary()`|
min_dist_dur | Minimum walk duration and distance |`character` | 132.30 m, 4.37 min | `metric_summary()` & `tract_metric_summary()` |
max_dist_dur | Maximum walk duration and distance |`character` | 13,210.90 m, 150.73 min| `metric_summary()` & `tract_metric_summary()` |
med_dist_dur | Median walk duration and distance |`character` | 1,393,90 m, 15.29 min| `metric_summary()` & `tract_metric_summary()`|
mean_dist_dur | Mean walk duration and distance | `character` | 1,586.50 m, 19.12 min | `metric_summary()` & `tract_metric_summary()` |
weekday_am_peak | Number of walks occurring between the hours of 6am and 10am Mon-Fri | `numeric` | 16 | `metric_summary()` & `tract_metric_summary()` |
weekday_pm_peak | Number of walks occurring between the hours of 3pm and 7pm Mon-Fri | `numeric` | 16 | `metric_summary()` & `tract_metric_summary()` |
weekday_off_peak | Number of walks occurring outside the peak hours on Mon-Fri | `numeric` | 16 | `metric_summary()` & `tract_metric_summary()` |
weekend_off_peak | Number of walks occurring anytime on Sat-Sun. Walks during the weekends are classified as off-peak regardless of time of day | `numeric` | 16 | `metric_summary()` & `tract_metric_summary()` |


