# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Haversine function, assumes spherical earth.
#' @param lonA Numerical longitude coordinate for ping A
#' @param latA Numerical latitude coordinate for ping A
#' @param lonB Numerical longitude coordinate for ping B
#' @param latB Numerical latitude coordinate for ping B
#' @param EARTH_RADIUS_METERS Default 6378137 meters
#' @return Haversine distance individual value
#' @keywords internal
haverDist <- function(lonA, latA, lonB, latB, EARTH_RADIUS_METERS = 6378137L) {
    .Call(`_walkingcalculatr_haverDist`, lonA, latA, lonB, latB, EARTH_RADIUS_METERS)
}

#' Haversine vector function, assumes spherical earth.
#' @param lon Numerical vector of longitude coordinates for multiple pings
#' @param lat Numerical vector of latitude coordinates for multiple pings
#' @param EARTH_RADIUS_METERS Default 6378137 meters
#' @return Haversine distance vector
#' @keywords internal
haverDistVector <- function(lon, lat, EARTH_RADIUS_METERS = 6378137L) {
    .Call(`_walkingcalculatr_haverDistVector`, lon, lat, EARTH_RADIUS_METERS)
}

#' Calculate angle of a set of coordinates.
#' @param lonA Numerical longitude coordinate for ping A
#' @param latA Numerical latitude coordinate for ping A
#' @param lonB Numerical longitude coordinate for ping B
#' @param latB Numerical latitude coordinate for ping B
#' @param lonC Numerical longitude coordinate for ping C
#' @param latC Numerical latitude coordinate for ping C
#' @return angle of latitude and longitude pings
#' @keywords internal
findAng <- function(lonA, latA, lonB, latB, lonC, latC) {
    .Call(`_walkingcalculatr_findAng`, lonA, latA, lonB, latB, lonC, latC)
}

#' Calculate angle vector of a vector of multiple coordinates.
#' @param lon Numerical vector of longitude coordinates for multiple pings
#' @param lat Numerical vector of latitude coordinates for multiple pings
#' @param dist distance value of the lon and lat vector pairs
#' @return angle vector of latitude and longitude vectors with distance
#' @keywords internal
findAngVector <- function(lon, lat, dist) {
    .Call(`_walkingcalculatr_findAngVector`, lon, lat, dist)
}

#' Find when standing still
#' @param ret Vectorized operation
#' @param accuracy Accuracy value in meters
#' @param lonDeg Numeric vector of longitude in degrees
#' @param latDeg Numeric vector of latitude in degrees
#' @param userFactor Character vector of user IDs
#' @keywords internal
makeLoIsStillHelper <- function(ret, accuracy, lonDeg, latDeg, userFactor) {
    .Call(`_walkingcalculatr_makeLoIsStillHelper`, ret, accuracy, lonDeg, latDeg, userFactor)
}

